spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: root1234
  data:
    redis:
      host: localhost

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: top.pi1grim.mall.entity
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: /mall


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl